storage:
  #accountname: mynewdocstorage
  #key: PRs63yUOhxAXe+hNkCJvFRjC5IipnIZ8TmmX/N3QPOtwPDjtJEHI6Dwy6bLtLm5hscNwvIOjREBUNbmFCTv+9Q==
  accountname: ankitastorageaccount
  key: wpnwtURJqOKtM/FpBh6pHHZFF1Ct4cAE+14q24ogEq2DkUsPtPEFATdShfuBvcRrD6nN85Tc4pk3Ckpd1sZtqQ==

